### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by bgfds** [shirsig/cdframes#32]
Would you consider making a version that shows global CDs for certain spells? I know there are other addons that do this but they don't really work that well, especially for counterspell

**Comment by shirsig** [comment]
What do you mean by "for certain spells"?

**Comment by bgfds** [comment]
Interrupts mostly.. like if someone uses counterspell/felhunter silence would it be possible to track it even if I wasn't targeting them/they didn't use it on me? https://youtu.be/vlEeNE1372s?t=56 somewhat like this addon from retail

antagonist has a "global" cd frame that shows kick if someone near you uses it but it doesn't show counterspell, and it's also a bar not a button so not that great

**Comment by shirsig** [comment]
That's the default behavior for all spells. The problem with some spells is that the combat log doesn't say who casted it, only who was hit (and in some cases nothing at all). Counterspell for example is one of those if i remember correctly. The addon will actually try to guess who casted it based on recent targets and their classes because of how useful it is in 1v1 situations especially, but only when you were the target because otherwise there is not enough information to guess well and the inaccuracy would be too big.

So if a cooldown is not shown it's probably because of one of those limitations. Of course there may also be bugs but there are no cooldowns left out on purpose despite sufficient information.
